import { motion } from "framer-motion";
import { Link } from "wouter";
import {
  ChevronLeft,
  FileCheck,
  Scale,
  UserCheck,
  AlertTriangle,
  ShieldOff,
  Gavel,
  CreditCard,
  Server,
  Ban,
} from "lucide-react";
import Footer from "@/components/Footer";

export default function Terms() {
  const sections = [
    {
      icon: FileCheck,
      title: "Acceptance of Terms",
      content: `By accessing or using CX Linux ("the Software"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Software.

These Terms apply to all users, including:
• Visitors browsing our website
• Community users of the free tier
• Paid subscribers (Pro, Enterprise, Managed)
• Contributors to our open-source repositories

We reserve the right to update these Terms at any time. Material changes will be communicated via email to registered users. Your continued use of the Software after changes constitutes acceptance of the new Terms.

If you are using the Software on behalf of an organization, you represent that you have authority to bind that organization to these Terms.`
    },
    {
      icon: Server,
      title: "Service Description",
      content: `CX Linux is an AI-powered command-line tool that converts natural language into executable Linux commands. The Software:

**Core Functionality**
• Translates plain English requests into appropriate shell commands
• Executes commands with user confirmation (unless bypass mode enabled)
• Provides explanations and context for executed commands
• Supports multiple LLM backends (Claude, OpenAI, local models)

**Processing Modes**
• Cloud Mode: Commands are processed via external LLM APIs
• Local Mode: Commands are processed entirely on your device

**Important Understanding**
The Software interacts directly with your operating system. Commands generated by AI are executed with your user permissions. You are responsible for reviewing and understanding commands before execution.

We continuously improve the Software. Features may be added, modified, or removed. Significant changes affecting paid subscribers will be communicated in advance.`
    },
    {
      icon: Scale,
      title: "License & Intellectual Property",
      content: `CX Linux is open-source software licensed under the Apache License 2.0.

**You May:**
• Use the Software for any purpose, including commercial applications
• Copy, modify, and distribute the Software
• Create derivative works based on the Software
• Use the Software as part of larger applications

**You Must:**
• Include the original copyright notice and license
• State any significant changes made to the code
• Include the NOTICE file if one exists

**You May Not:**
• Use our trademarks without permission (CX Linux name, logo, branding)
• Remove or alter copyright notices
• Hold us liable for any damages arising from use

**Trademark Notice**
While the code is Apache 2.0 licensed, the CX Linux name, logo, and branding are protected trademarks of AI Venture Holdings LLC. You may not use these marks without prior written permission, except as required for reasonable attribution.`
    },
    {
      icon: CreditCard,
      title: "Subscription Terms",
      content: `**Free Tier (Community)**
• Access to core features at no cost
• Community support via Discord and GitHub
• No SLA or guaranteed response times

**Pro Plan ($20/month or $192/year)**
• All Community features plus Pro features
• 14-day free trial for new subscribers
• Cancel anytime; access continues until period ends
• No refunds for partial periods

**Enterprise Plan ($99/month or $948/year)**
• All Pro features plus Enterprise features
• 14-day free trial for new subscribers
• Priority support with 24-hour response time SLA
• Cancel anytime; access continues until period ends

**Managed Plan ($299/month or $2,868/year)**
• Fully managed deployment and support
• Dedicated infrastructure and custom integrations
• Requires annual commitment after trial
• 30-day notice required for cancellation

**Billing**
• Payments processed securely via Stripe
• Annual plans billed as single payment
• Failed payments: 3 retry attempts over 7 days
• Access suspended after payment failure

**Refund Policy**
• 14-day money-back guarantee on first subscription
• No refunds after 14 days or for renewals
• Enterprise/Managed refunds handled case-by-case`
    },
    {
      icon: UserCheck,
      title: "User Responsibilities",
      content: `When using CX Linux, you agree to:

**General Conduct**
• Use the Software in compliance with all applicable laws
• Not attempt to circumvent security features or access restrictions
• Not use the Software to distribute malware or harmful code
• Not use the Software for unauthorized access to systems
• Not misrepresent your affiliation with CX Linux

**Command Execution**
• Review all generated commands before execution
• Maintain appropriate backups of important data
• Test in non-production environments when appropriate
• Understand that AI-generated commands may contain errors

**API & Rate Limits**
• Respect rate limits imposed by LLM providers
• Provide your own API keys when required
• Not share API keys or abuse shared resources
• Not use automation to circumvent usage limits

**Account Security**
• Maintain the confidentiality of your credentials
• Notify us immediately of any unauthorized access
• Not share subscription access with unauthorized users

Violation of these terms may result in immediate termination of access and reporting to appropriate authorities.`
    },
    {
      icon: AlertTriangle,
      title: "Disclaimers",
      content: `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.

**We Do Not Warrant That:**
• The Software will meet your specific requirements
• The Software will be uninterrupted, secure, or error-free
• AI-generated commands will be correct, safe, or appropriate
• Results obtained will be accurate or reliable
• Any errors in the Software will be corrected

**AI-Specific Disclaimers**
• AI models may produce incorrect or harmful commands
• Natural language interpretation may be imprecise
• Commands may have unintended effects on your system
• AI behavior may change with model updates

**Your Responsibility**
You acknowledge that using the Software involves inherent risks, including system modifications, data loss, and security implications. You assume full responsibility for:
• Backing up your data before using the Software
• Testing in non-production environments
• Reviewing all commands before execution
• Understanding the implications of executed commands`
    },
    {
      icon: ShieldOff,
      title: "Limitation of Liability",
      content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL AI VENTURE HOLDINGS LLC, CX LINUX, ITS MAINTAINERS, CONTRIBUTORS, OR AFFILIATES BE LIABLE FOR:

• Any indirect, incidental, special, consequential, or punitive damages
• Loss of profits, data, use, goodwill, or other intangible losses
• Damages resulting from AI-generated commands or recommendations
• Damages resulting from unauthorized access to your systems
• Damages resulting from third-party services (LLM providers, etc.)
• System failures, data corruption, or security breaches
• Any other damages arising from your use of the Software

**Liability Cap**
In no event shall our total liability exceed the greater of:
• The amount you paid us in the 12 months preceding the claim, or
• One hundred dollars ($100)

**Exceptions**
Some jurisdictions do not allow the exclusion of certain warranties or limitations of liability. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law.

This limitation applies regardless of the legal theory (contract, tort, negligence, strict liability, or otherwise) and whether or not we have been advised of the possibility of such damages.`
    },
    {
      icon: Ban,
      title: "Termination",
      content: `**By You**
You may terminate your use of the Software at any time by:
• Uninstalling the Software from your systems
• Canceling your subscription (if applicable)
• Deleting your account

**By Us**
We may suspend or terminate your access immediately if:
• You violate these Terms
• You engage in fraudulent or illegal activity
• You abuse our systems or community resources
• Required by law or legal process

**Effect of Termination**
Upon termination:
• Your right to use paid features ends immediately
• You remain responsible for charges incurred before termination
• Provisions that should survive termination will continue to apply
• No refunds for unused subscription time (except as stated above)

**Data After Termination**
• Your local data remains on your systems
• Account data deleted within 30 days of request
• Anonymized analytics may be retained
• We have no obligation to maintain your data`
    },
    {
      icon: Gavel,
      title: "Governing Law & Disputes",
      content: `These Terms shall be governed by and construed in accordance with the laws of the State of Utah, United States, without regard to its conflict of law provisions.

**Dispute Resolution**
Any disputes arising from these Terms shall be resolved through:

1. **Good Faith Negotiation** - Attempt informal resolution first
2. **Mediation** - If negotiation fails, non-binding mediation in Salt Lake City, Utah
3. **Binding Arbitration** - Under the rules of the American Arbitration Association if mediation fails

**Arbitration Terms**
• Arbitration shall take place in Salt Lake City, Utah
• The decision shall be final and binding
• Each party bears its own costs unless otherwise awarded
• You agree to waive right to class action lawsuits

**Small Claims Exception**
Either party may bring individual claims in small claims court if they qualify.

**International Users**
If you access the Software from outside the United States, you agree to comply with all local laws regarding online conduct. You acknowledge that the Software is controlled from the United States.

**Company Information**
AI Venture Holdings LLC
Salt Lake City, Utah, USA
legal@cxlinux.com`
    },
  ];

  return (
    <div id="terms-page-container" className="min-h-screen pt-20 pb-16">
      <div className="max-w-4xl mx-auto px-4">
        <Link
          id="terms-back-link"
          href="/"
          className="inline-flex items-center gap-2 text-gray-400 hover:text-purple-400 transition-colors mb-8"
        >
          <ChevronLeft size={16} />
          Back to Home
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <h1 id="terms-title" className="text-4xl md:text-5xl font-bold mb-4">
            <span className="text-white">Terms of</span>{" "}
            <span className="gradient-text">Service</span>
          </h1>
          <p id="terms-subtitle" className="text-gray-400 text-lg">
            Legal terms governing your use of CX Linux
          </p>
          <p id="terms-effective-date" className="text-gray-500 text-sm mt-2">
            Last updated: January 15, 2026
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
          className="bg-purple-500/10 border border-purple-400/30 rounded-xl p-4 mb-8"
        >
          <p className="text-purple-300 text-sm">
            <strong>Summary:</strong> CX Linux is provided under the Apache 2.0 license. Use
            at your own risk. AI-generated commands may contain errors—always review before
            executing. Paid plans include a 14-day trial and money-back guarantee.
          </p>
        </motion.div>

        <div id="terms-sections" className="space-y-8">
          {sections.map((section, index) => (
            <motion.div
              key={section.title}
              id={`terms-section-${index}`}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="bg-white/5 border border-white/10 rounded-xl p-6"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-purple-500/10 rounded-lg">
                  <section.icon size={20} className="text-purple-400" />
                </div>
                <h2 className="text-xl font-semibold text-white">{section.title}</h2>
              </div>
              <div className="text-gray-400 whitespace-pre-line leading-relaxed text-sm prose prose-invert prose-sm max-w-none">
                {section.content}
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      <Footer />
    </div>
  );
}
